modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="storage_upgrade"
version="0.0.1"
displayName="Storage upgrade"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="300f20t, MCreator"

[[dependencies.storage_upgrade]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.storage_upgrade]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.storage_upgrade]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

